### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-migrations#106]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
Permissions are incorrect. Please work with @bbarani's team to remove the group and add individuals with maintain access.

![Screenshot 2023-04-20 at 10 28 51 AM](https://user-images.githubusercontent.com/542335/233397627-c67123da-a395-473d-8f77-e6350d2e49e3.png)

**Comment by bbarani** [comment]
Fixed the permissions so closing this issue.

**Comment by dblock** [comment]
Verified, thx.
