### ISSUE TITLE
Allow Renaming of an Index from Source to Target with Transformations

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-migrations#1082]
### Description
Indices cannot easily be renamed once they have been created.  Migrations are one of the few opportunities to change the index name, it would be useful if this was supported.

### What solution would you like?
When selecting indices for migration if source->target names could be specified this would allow for updating naming decisions that were made when the index was created but should be revisited.

**Comment by sumobrian** [comment]
This will be enabled with https://opensearch.atlassian.net/browse/MIGRATIONS-2146 and https://opensearch.atlassian.net/browse/MIGRATIONS-2152
