### ISSUE TITLE
[BUG] Snapshot differs from RFS in shard numbers

### ISSUE THREAD

**Issue by rudney-souza** [opensearch-project/opensearch-migrations#1172]
### What is the bug?
When trying to migrate from opensearch 1.3 to opensearch 2.17 i get some indexes to not be with documents 

### How can one reproduce the bug?
Creating snapshot with migration assistant and then using backfill migration 

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
OS_1.3 to OS_2.17

### Do you have any screenshots?
<img width="511" alt="image" src="https://github.com/user-attachments/assets/766bd78f-8ffb-421f-9c29-4c65b2e56a95">

**Comment by AndreKurait** [comment]
Hi @rudney-souza, there's several reasons why the backfill work items may not align with the snapshot shards and they should not be compared.

The most likely cause of the discrepancy here is from indices which are excluded by default during backfill, by default, any index that starts with `.`

I'd recommend using `console clusters cat-indices` to compare the source and target shard and document counts. Note, if active index updates are occurring, doc counts may not line up.

**Comment by AndreKurait** [comment]
Closing as no action item is needed
