### ISSUE TITLE
Handling exception in callback

### ISSUE THREAD

**Issue by matthead** [opensearch-project/opensearch-migrations#159]
https://github.com/opensearch-project/opensearch-migrations/blob/5a42c807e0deac9cbcd30003bc16595a686f29e3/TrafficCapture/captureKafkaOffloader/src/main/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactory.java#L82

Have you thought about how the exception would get propagated to the invoker?

One possibility would be to `completeExceptionally` if there was an exception

**Comment by gregschohn** [comment]
Thanks for the issue!  This should be resolved in [this PR](https://github.com/opensearch-project/opensearch-migrations/pull/254) in [this code](https://github.com/opensearch-project/opensearch-migrations/pull/254).
