### ISSUE TITLE
[META] Use Data Prepper for historical data migration

### ISSUE THREAD

**Issue by kartg** [opensearch-project/opensearch-migrations#162]
This is a meta issue to track the list of tasks required to adopt [Data Prepper](https://github.com/opensearch-project/data-prepper) as our mechanism of choice for historical data migration. 

Today, the ["datastash" implementation](https://github.com/opensearch-project/opensearch-migrations/tree/main/datastash) uses Logstash paired with the [logstash-output-opensearch plugin](https://github.com/opensearch-project/logstash-output-opensearch), distributed as a [pre-assembled Docker image](https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin). As detailed in [this blog post](https://opensearch.org/blog/Discontinuing-custom-Logstash-distribution/), support for this distribution is being discontinued.

At the same time, Data Prepper is in the process of adding support for [OpenSearch as a source](https://github.com/opensearch-project/data-prepper/issues/1985) (it already supports OpenSearch as a sink). This makes it a good replacement for Logstash since these sources and sinks are included in the [core Data Prepper distribution](https://hub.docker.com/r/opensearchproject/data-prepper)

----

- [x] #163 
- [x] #164 
- [x] #165 
- [x] #166

**Comment by sumobrian** [comment]
This solution has been deprecated and replaced with metadata migration tooling and reindex from snapshot. Marking this one closed.
