### ISSUE TITLE
[Historical Data Migration] Integrate Data Prepper Docker image

### ISSUE THREAD

**Issue by kartg** [opensearch-project/opensearch-migrations#163]
relates #162 

* Change the datastash Docker compose file to use Data Prepper images instead of Logstash
* Write a Data Prepper configuration file to replace the Logstash one 
* Test the data migration pipeline

**Comment by sumobrian** [comment]
Tracking through Jira - Epic https://opensearch.atlassian.net/browse/MIGRATIONS-1154
