### ISSUE TITLE
[Historical Data Migration] Simplify input mechanism for historical data migration Docker image

### ISSUE THREAD

**Issue by kartg** [opensearch-project/opensearch-migrations#166]
relates #162, blocked by #165

Today, the Docker image for historical data migration uses a volume mount to supply the Data Prepper config file to be used. This approach makes it incompatible with the [Docker ECS context](https://docs.docker.com/cloud/ecs-integration/), preventing it from [easily being deployed](https://www.docker.com/blog/docker-compose-from-local-to-amazon-ecs/) to the cloud.

The aim of this task is to investigate, design and implement an input mechanism (that may move away from volume mounts) that would make the Docker image cloud-compatible.

**Comment by sumobrian** [comment]
This issue is no longer applicable. Historical data migration is now accomplished at scale with Reindex-from-snapshot (RFS).
