### ISSUE TITLE
Design "Expectation" Data Model

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#2]
### Task

Design a system to capture expectations about clusters and upgrades in a way that they can be used for all currently expected use-cases:

-   Executing upgrade expectations against an upgraded cluster
-   Optional for now, but preferred: Executing upgrade expectations "predictively" against a cluster without performing an upgrade
-   Consider how we will report these expectations to the user, but don't design/create a full reporting mechanism
-   Consider how we will down-select among a large library of expectations once we support many core engine and plugin versions/combinations (tags?), but don't design/create a full mechanism
-   Will probably include a concept of conditionality (when does it apply), what the expectation is (what should be true/false), and maybe some context information for humans
-   Up for design consideration - should the dataset used to test the expectations be inferrable/generate-able from the expectations themselves?

### Acceptance Criteria

- Create a GH issue with a design for data model, review w/ engineering team, get signoff
- Design should be specific enough that a prototype can be created in a follow up task

**Comment by mikaylathompson** [comment]
https://github.com/opensearch-project/opensearch-migrations/issues/24
