### ISSUE TITLE
[FEATURE] Support migration from post-fork Elasticsearch versions to OpenSearch

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-migrations#202]
Creating this issue as a placeholder for the popular request. Will add more details later.

Users would like a mechanism to easily migrate from 7.11+ Elasticsearch versions to OpenSearch.

**Comment by sumobrian** [comment]
Opened Epic https://opensearch.atlassian.net/browse/MIGRATIONS-1177 to track.
