### ISSUE TITLE
Add Github workflow for running python tests and generating coverage on PRs

### ISSUE THREAD

**Issue by sumobrian** [opensearch-project/opensearch-migrations#38]
#### 12/8
Merged changes for python tests and coverage on PR
* https://github.com/opensearch-project/opensearch-migrations/pull/33

**Comment by lewijacn** [comment]
Upon creating a codecov.io account and allowing it to sync, coverage was successful and uploaded to PR. This may be a user specific fix though, need to verify if other contributors have a similar experience. This [issue](https://community.codecov.com/t/unable-to-publish-codecov-reports-for-public-repository/3931/7) also highlights other opensearch repos that went from private to public and faced the same issue

**Comment by lewijacn** [comment]
Coverage reports seem to be consistently added to PRs now, whereas for at least a few days this was intermittent for some reason that is unclear. Closing now
