### ISSUE TITLE
[DOCS] Adding a section for "OCI Deployment"

### ISSUE THREAD

**Issue by gtahhan** [opensearch-project/opensearch-migrations#492]
We need to add documentation on how to deploy the opensearch-migrations solution to Oracle OCI.

The change should happen in the following sections:
- Edit file https://github.com/opensearch-project/opensearch-migrations/blob/main/README.md and add a section for OCI Deployment
- Edit file https://github.com/opensearch-project/opensearch-migrations/blob/main/deployment/README.md and add a section for OCI deployment
- Adding a new folder inside https://github.com/opensearch-project/opensearch-migrations/tree/main/deployment/terraform and add the new "OCI Deployment" README and documentation inside a new folder

**Comment by jyoti0208** [comment]
Hi @gtahhan I would like to work on this.

**Comment by jyoti0208** [comment]
I have added initial changes [here](https://github.com/opensearch-project/opensearch-migrations/compare/main...jyoti0208:opensearch-migrations:oci-support?expand=1).
After internal review of doc, I'll create a PR with that change.

**Comment by mparikhaiven** [comment]
Any further updates on OCI deployment?

**Comment by sumobrian** [comment]
I haven't seen any traction on this one. We currently don't have this functionality on our roadmap but happy to assist if someone is interested in this. Marking this one closed for now.
