### ISSUE TITLE
[BUG] Parameter --noCapture triggers java.lang.UnsupportedOperationException and interrupted traffic forwarding

### ISSUE THREAD

**Issue by ParvelAWS** [opensearch-project/opensearch-migrations#540]
### What is the bug?
When the proxy needs to bypass or pause offloading to Kafka topic while still keeping forwarding traffic towards OpenSearch, the parameter --noCapture is used. But it's triggering exception reported for every message and traffic is not forwarded to OpenSearch.
Pod Logs:
`{"@timestamp":"2024-03-27T23:38:33.372Z","ecs.version":"1.2.0","log.level":"WARN","message":"An exception 'java.lang.UnsupportedOperationException: spaceLeft() can only be called on CodedOutputStreams that are writing to a flat array or ByteBuffer.' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:","[process.thread.name](http://process.thread.name/)":"captureProxyPoolWorker-3-1","log.logger":"io.netty.channel.AbstractChannelHandlerContext","error.type":"java.lang.UnsupportedOperationException","error.message":"spaceLeft() can only be called on CodedOutputStreams that are writing to a flat array or ByteBuffer.","error.stack_trace":"java.lang.UnsupportedOperationException: spaceLeft() can only be called on CodedOutputStreams that are writing to a flat array or ByteBuffer.\n\tat com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.spaceLeft(CodedOutputStream.java:2233)\n\tat org.opensearch.migrations.trafficcapture.StreamChannelConnectionCaptureSerializer.beginSubstreamObservation(StreamChannelConnectionCaptureSerializer.java:150)\n\tat org.opensearch.migrations.trafficcapture.StreamChannelConnectionCaptureSerializer.addCloseEvent(StreamChannelConnectionCaptureSerializer.java:240)\n\tat com.verizon.opensearch.proxy.offload.MultiTargetOffloader.addCloseEvent(MultiTargetOffloader.java:45)\n\tat org.opensearch.migrations.trafficcapture.netty.LoggingHttpHandler.channelUnregistered(LoggingHttpHandler.java:160)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:217)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:195)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:188)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1388)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:215)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:195)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:821)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n","time":"2024-03-27T23:38:33.372Z"}`

### How can one reproduce the bug?
With the following parameters supplied
`"--listenPort", "80", 
              "--noCapture",
              "--destinationUri", "https://vpc-xxx-opensearch.us-east-1.es.amazonaws.com:443", 
              "--insecureDestination", "--suppressCaptureForHeaderMatch", "User-Agent", "^ELB-HealthChecker/2\\.0"]`

### What is the expected behavior?
The proxy should stop writing to Kafka queue but still forwarding traffic to OpenSearch

### What is your host/environment?
EKS 1.28
AWS Linux Min 2023

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by AndreKurait** [comment]
Hi Parvel, i'll be taking this up.
https://opensearch.atlassian.net/browse/MIGRATIONS-1616

**Comment by AndreKurait** [comment]
https://github.com/opensearch-project/opensearch-migrations/pull/543 has been merged. Closing this bug
