### ISSUE TITLE
Move "migration core" functionality into a new python package

### ISSUE THREAD

**Issue by mikaylathompson** [opensearch-project/opensearch-migrations#61]
As a followup/companion to #60, we've discussed moving all of the code that would be shared by a different migration workflow package out of the current `upgrades` directory and into its own `migration-core` directory & package.

This includes the REST client, the cluster management code, and the core workflow code (like FrameworkSteps).

**Comment by lewijacn** [comment]
PR merged
* https://github.com/opensearch-project/opensearch-migrations/pull/66
