### ISSUE TITLE
[BUG] Gradle Build and Test / gradle-build-and-test is flaky

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-migrations#630]
### What is the bug?
Seeing failures on `Gradle Build and Test / gradle-build-and-test` when no impacting code changes are made.

### How can one reproduce the bug?
Unclear needs more investigation

### What is your host/environment?
GitHub Action environment

### Do you have any additional context?
Example failure https://github.com/opensearch-project/opensearch-migrations/actions/runs/8930581418/job/24530967074?pr=627
- Impacted PR https://github.com/opensearch-project/opensearch-migrations/pull/627

**Comment by AndreKurait** [comment]
Will be fixed in PR 615 
https://github.com/opensearch-project/opensearch-migrations/pull/615/commits/1b661654b4bb1b53afe766f255e106c4df2dca5b

**Comment by peternied** [comment]
@AndreKurait Looking at the change, there is a lot going on - how close is it to merging?  If it might be a little while could we pull in that specific commit that fixes the memory leak on its own?

**Comment by AndreKurait** [comment]
It's merged. Will mark this as closed, please reopen if this still occurs
