### ISSUE TITLE
[EPIC] Cluster Duplication Tooling

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#71]
### Objective
This serves as the high-level tracking issue for work to create/maintain cluster duplication tooling.

### User Narrative
**"As a user of Elasticsearch or OpenSearch, I want a mechanism to duplicate the data and configuration of an existing cluster onto new hardware.  I want the operational effort to be minimized.  I am sensitive to impact on my existing cluster, and cannot accept downtime on the existing cluster.  As changes are made to my existing cluster, I want the duplicate cluster to reflect that.  I am not sensitive to propogation delays between the existing and duplicate cluster.  I am sensitive to the cost in time and money to create the duplicate."**

Some clarifications on the narrative:
* The configuration duplicated by this tooling will be index-level and cluster-level settings configurable over the REST API, and hopefully plugin configuration in the long term
* The tooling will aim to replicate any changes to the cluster that occur over the REST API, whether data writes or changes to things like index-level mappings.

### Proposed Approach
The options for cluster duplication include: Cross-Cluster Replication, Reindexing, and Snapshot/Restore with T-Splitter (using either Logstash or Data Prepper).  Per conversation, @chelma and @kartg decided to focus on Snapshot/Restore with a T-Splitter.  Cross-Cluster Replication is performed at an index-level, requires a plugin, and doesn't copy cluster-level configuration.  Reindexing is expensive and doesn't copy index- or cluster-level config.  Snapshot/Restore copies index- and cluster-level config and is widely used as a duplication mechanism.  

We're unclear on the relative merits of Logstash and Data Prepper, so our initial efforts will focus on developing prototypes of those paradigms to enable performance testing.

### Tasks
Phase 0: Investigate Intersection of Duplication and Shadow Cluster Performance Eval
* https://github.com/opensearch-project/opensearch-migrations/issues/89

Phase 1: Prototyping, Selecting a T-Splitter, and Core Engineering:
* https://github.com/opensearch-project/opensearch-migrations/issues/88
* https://github.com/opensearch-project/opensearch-migrations/issues/76
* https://github.com/opensearch-project/opensearch-migrations/issues/77
* https://github.com/opensearch-project/opensearch-migrations/issues/82
* https://github.com/opensearch-project/opensearch-migrations/issues/78
* https://github.com/opensearch-project/opensearch-migrations/issues/93

Phase 2: Creating Tooling:
* https://github.com/opensearch-project/opensearch-migrations/issues/92
* https://github.com/opensearch-project/opensearch-migrations/issues/96
* https://github.com/opensearch-project/opensearch-migrations/issues/97
* https://github.com/opensearch-project/opensearch-migrations/issues/95
* https://github.com/opensearch-project/opensearch-migrations/issues/94

**Comment by gregschohn** [comment]
To clarify, there isn't a proposed approach yet, but a list of possible approaches that are being explored?

**Comment by gregschohn** [comment]
Can you explain why you'd need a T-Splitter in addition to snapshot & restore?  I am presuming that a T-Splitter is a 'tee' that duplicates network traffic to multiple destinations.  If the goal is to replicate a cluster and the user is insensitive to eventual consistency delays, snapshot & restore should be sufficient.  Is there something missing in the user narrative, e.g. that the new cluster should be kept current w/ live updates?  That seems to conflict with the propagation delay clause.

If you're trying to use both together, you'll need to figure out how to manage cutover so that messages aren't lost or that messages aren't duplicated.  That will also likely require your splitter to buffer traffic.

Is the zero-downtime requirement on writes or on reads?  In other words, what will be the maximum delay for a write to be committed in the cluster?

**Comment by chelma** [comment]
Per design conversations, the current thinking is to HAProxy to synchronously proxy the incoming stream of requests/responses to the user's existing cluster and capture them for offload.  The offloaded stream data can be ingested by a Data Prepper instance which replays the requests against a shadow cluster, compares the new response against the original, and reports the result in a new format to another location.

Setup of the shadow cluster can be performed by snapshot/restore + replay in the short term.  In the longer term, Data Prepper could be used in place of snapshot/restore for the baseline data migration in order to move to a more generic off-the-shelf option that applies to many different sources (elasticsearch, opensearch, solr, sql, whatever).
