### ISSUE TITLE
[EPIC] Shadow Testing & Validation

### ISSUE THREAD

**Issue by mikaylathompson** [opensearch-project/opensearch-migrations#74]
The following is an issue to track/discuss the overall vision for the Shadow Testing & Validation tools and the specific user stories and tasks to get us there.

**Table of Contents**
1. [Scope of the tools](#scope-of-tools)
2. [User Narrative](#user-narrative)
	1. [Recorder](#t-splitter-recorder)
	3. [Analyzer](#analyzer)
3. [MVP User Stories & Tasks](#user-stories-tasks)
4. [Beyond the MVP](#beyond-mvp)

## Scope of the Tools <a href="#user-content-scope-of-tools" id="scope-of-tools" />

The "Shadow Validation Tool" is actually a collection of tools that can be used to help users duplicate production traffic onto a shadow cluster and understand the result and performance differences between the two clusters.

A t-splitter type tool will be used to duplicate the traffic coming into the source cluster to the shadow cluster and record the responses from both the source and shadow clusters. This tool is an essential prereq to the work in this epic, but is out of scope and handled by [[]].

After that, the Analyzer tool will be responsible for comparing the responses and offering the user useful and actionable information.

In the medium term, we expect to use a third OpenSearch cluster as the datastore for requests and responses. The data could plausibly be stored in many ways/places (e.g. an S3 bucket), but this provides an abstracted interface for storing the data in a platform-agnostic way. The OpenSearch cluster can also become the platform for data analysis, using plugins or extensions.

However, for the short term, we're intending to use a docker node to host the t-splitter, write the response data to local files, and run the analyzer tool on that local data.

#### Iterative Use
An underlying assumption of these tools should be that users are unlikely to just run them a single time. Users will likely enable dual-writes and record the responses and run Analyzer, find issues with their results, change the shadow cluster and then re-enable data transfer and run the Analyzer on the new results.

In some cases, they may also run the Analyzer many times with different configurations (e.g. data transformers or masks) to narrow in on the most interesting changed results. We need to make it easy for them to save their configurations and rerun them or run them on a new round of replayed data.

#### Out of Scope
This epic and narrative are focusing solely on the validation tool, so it leaves setting up the shadow cluster as a black box. This can be handled by a seperate tool/constellation of tools, or manually by the user. The shadow cluster may or may not be the "same" as the original cluster -- it may be more or fewer nodes, the same or a different version, and in the same or a different location (e.g. on-prem, ec2, aws managed service, an alternate cloud).

Transfering historical data is also treated as a black box. Snapshot & restore and reindexing (either from the original cluster or from an external source) are likely to be common methods, but the user can transfer data however they choose, with or without help from tools we've provided for them. The caveat is that if the historical data is not transfered fully, the results cannot be expected to be the same.

Down the line, we may transition from a live T-splitter (i.e. sending requests and recording responses from both clusters in real-ish time) to a T-splitter that records requests and a Replayer that conveys them to the shadow cluster at a later time. That offers advantages in terms of replay-ability and navigating more complex network situations (including the source and shadow clusters being in very different locations and thus having larger latency effects).

#### Example Situations
- A user is considering migrating their cluster to a different cloud provider.
- A user wants to experiment with a different cluster topology on the same cloud provider and see how performance changes.
- A user is curious about OpenSearch 2.x and wants to know how their carefully-tuned document rankings will change before they upgrade.
- A user wants to migrate from on-prem to a cloud provider but needs to convince skeptical leadership with performance and cost data.
- A user wants to compare performance data between two versions of OpenSearch.

### T-Splitter & Recorder <a href="#user-content-recorder" id="t-splitter-recorder" />

The user begins by setting up the shadow cluster.

On the source cluster, they set up a docker node with our T-Splitter tool and configure the tool with the source and shadow clusters. Then they redirect their clients to send requests to the t-splitter. It passes requests through to the source cluster and responses back to the user, but also forwards all requests to the shadow cluster and records the responses. In this way, the two clusters are kept in sync and all requests and responses to both clusters are logged locally.

This tool continues to forward & record until the user disables it.

At this point (after recording starts), the user should transfer historical data up to the point at which recording started.

As an alternative, the user can set up any other mechanism to forward & log requests and responses. If this is data they're already logging, it only needs to be transformed to the standard format and added to the validator cluster. This means that even if the user runs a different piece of software (e.g. Solr) as the source cluster, they can add their logs by translating the request into an equivalent OpenSearch request and handling replaying the data on their own.

### Analyzer <a href="#user-content-analyzer" id="analyzer" />
At any point after the T-Splitter/Recorder has started, the user can start the Analyzer tool.  In the short term, the Analyzer runs on the same docker node as the t-splitter and pulls the data from local files. Down the road, the Analyzer will pull data from the Validator datastore cluster and can be run from a seperate machine.

By default, the user is able to use the response data as-is or finetune a baseline transformation that masks volitaile fields (e.g. timestamps, cluster names, ip addresses, etc.) so that responses can be compared directly.

The user can add additional functions to 1/ transform the source responses, 2/ transform the target responses, or 3/ be used as the comparison function. The first and second allow users to do things like compare between Solr and OpenSearch responses, or mask additional fields that they don't want to compare. The third allows users to, for instance, set a tolerance of 10% on a given field value before it's shown as a difference.

The MVP Analyzer is a command line tool that has two primary outputs:
- it gives basic summary statistics (number of requests compared and percent that match) and creates a list of all response pairs that are different (according to the comparison function) and provides a diff of the differences, shown with the request.
- it displays basic performance data compared between the source and shadow clusters (e.g. average, p90, p99 latencies for requests)

## MVP User Stories & Tasks <a href="#user-content-user-stories-tasks" id="user-stories-tasks" />
The following user stories will be made into tasks and linked from here.

#### T-Splitter & Recorder

T-Splitter tasks are handled in #71.
 
- [ ] #79
	- As a validation tool developer, I would like a basic tool that allows me to log requests & responses (plus timestamps) from a cluster and write it into a new OS cluster.
- [x] #80 
	- As a user, I would like documentation on one or more ways to set up request/response collection for my cluster (understanding that it will not be a polished tool at this point).

#### Analyzer
- [x] #84
	- As a user, I would like to be able to run the analyzer tool and get summary statistics and a list of diffs for responses that are different between the original and shadow clusters.
- [x] #85
	- As a user, I would like to be able to get basic performance comparison data between my original and shadow clusters.
- [x] #86
	- As a user, I would like the analyzer tool to apply a default mask on response fields that are volatile or unrelated to my comparisons, and to be able to configure this transformer.
- [x] #87
	- As a user, I would like to be able to configure transformations on my source responses or target responses and to be able to specify a custom comparison function.

## Beyond the MVP <a href="#user-content-beyond-mvp" id="beyond-mvp" />
The following are our suggested v2.0 extensions for the above narrative. While these are the things we _think_ we'd like to focus on immediately afterwards, the focus should be on getting the MVP in front of users and responding to their feedback.

**T-Splitter / Recorder**
- Record requests/responses using an OS cluster as the datastore
- Record cluster state and failures (e.g. if the cluster is in a yellow or red state or if a master node fails)
- Research vector clock timestamps and log timestamps that correspond to time a request hits either the coordinator or master node
- Using an OS cluster as the datastore, build in index state management that allows us to cap the size of the cluster and drop older data.
- Record requests and source responses without relaying them to a shadow cluster (i.e. pure recorder without real-time dual-writes)

**Analyzer**
- Allow users to apply filters or aggregations for the basic outputs described above
- Allow users to export performance data as a CSV to analyze with their own tools
- Move the analyzer tool to being a OpenSearch plugin or extension and using an OS cluster as datastore
- Add a "load factor" to the exported performance data that's something along the lines of an average tps for the 30 seconds surrounding a request so that users can more easily understand the differences between the loads on their original vs shadow clusters.
- Give users tools to understand how "best effort" ordering impacts their results (for instance by segmenting query responses based on how close in time they are to a write request)
- Build tools to help explain the differences seen in the results to users, possibly by using clustering to group results by types of differences.
- Allow users to compare the results of replaying the same source data against multiple shadow clusters.

**Replayer**
These tasks aren't relevant until we begin recording requests for later replay, instead of doing real-time dual-writes.

- Replay requests at original speed. This may require fanning out requests to multiple nodes. As an extension, can we replay requests at a multiple of the original speed?
- "Focused replay": if a user wants to focus on a particularly intense or interesting period of queries (say from time N to time M), start by filtering for all mutating requests before time N and replaying them. Then run all queries between N and M to be analyzed.
- Perform stress tests by taking out nodes at specified times during the replay and allow the user to watch the system recover. There are likely many other chaos testing applications to add into this.

**Comment by peternied** [comment]
Great proposal.  I would recommend reusing [OpenSearch Benchmark](https://github.com/opensearch-project/opensearch-benchmark).  While there are some differences in the scenarios described - real workflows with traffic splitting between clusters vs synthetic workflows with asynchronous A / B analysis, reusing existing tool could make getting these features in customers hands very fast.
