### ISSUE TITLE
Prototype Logstash T-Splitting Locally

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#77]
Depends on task: https://github.com/opensearch-project/opensearch-migrations/issues/88

## Task
Using the tooling created in the preceding task (https://github.com/opensearch-project/opensearch-migrations/issues/88), develop a bare-bones prototype to analyze the performance of Logstash as a T-Splitter.

## Acceptance Criteria
* Code to automate creation of two Elasticsearch or OpenSearch Clusters, a Logstash instance, and the configuration to pipe requests sent to the Logstash instance to both Clusters
* Demo automated setup, T-Splitting, and automated teardown to the team

**Comment by sumobrian** [comment]
High level estimate -- may need to revisit: 13

**Comment by chelma** [comment]
As discussed in https://github.com/opensearch-project/opensearch-migrations/issues/76, investigation indicates that Logstash/data prepper are not well suited to provide synchronous proxy and recording of the traffic stream to the primary cluster.  Closing task.
