### ISSUE TITLE
Disable 'Require branches to be up to date before merging' setting on this repository

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-migrations#776]
In the configuration of this repository there is a requirement that branches are up-to-date before they can be merged.  This is forcing all pull requests after any change to merge from main and re-run tests before it can be merged.  This effectively creates a delay of the time it takes to run the tests after any change is merged.

### Maintainers please vote via reacting on this issue:
- Vote with 👍
   - Disable this setting, less merging will be needed to get into main, sometimes the pull request checks with be slightly out of date.
- Vote with 👎
   - Lets make no changes to pull requests, we continue to require that changes are merged only when the most recent version of the checks have succeeded.

**Comment by peternied** [comment]
@opensearch-project/admin Could we get this setting updated, at this time we've got 3 👍 votes to make this change?

**Comment by gaiksaya** [comment]
> @opensearch-project/admin Could we get this setting updated, at this time we've got 3 👍 votes to make this change?

Done!

**Comment by peternied** [comment]
@gaiksaya Thanks!
