### ISSUE TITLE
Create or Select Tooling to Simulate Cluster Traffic

### ISSUE THREAD

**Issue by chelma** [opensearch-project/opensearch-migrations#82]
## Task
In order to test our cluster duplication tooling, we need to have tooling to simulate traffic being sent to the Cluster.  While in the long term we'll probably want to have a fairly sophisticated tool that can be run on a collection of hosts and pointed at a Cluster across a real network, for the time being we can likely get away with something simple that's run off a developer laptop.

As a starting point, you may investigate this existing tool [1] to see if it solves the problem.

[1] https://github.com/opensearch-project/opensearch-benchmark-workloads

## Acceptance Criteria
* Tooling should be runnable on a developer laptop via command line and pointed at a hostname/port
* Tooling should be able to simulate data reads (get indexes/docs), data writes (put indexes/docs), configuration reads (get cluster status), and configuration writes (change index settings, etc).
* The ratio and rate of the requests sent by the tooling should be configurable.  For this task, we'll focus on constant-rate requests instead of variable rate requests. - sumobrian@: this is optional
* The behavior of the tooling should be repeatable.  That is, if an issue is identified with one run of the tooling, we should be able to do that exact same run again to provoke the same response from the system under test.
* Demo tool to team

**Comment by chelma** [comment]
Task might be obviated by this existing tool: https://github.com/opensearch-project/opensearch-benchmark-workloads

**Comment by sumobrian** [comment]
Estimate: 5 - Assumption is that we will not have to write code but if we do it will be basic.
