### ISSUE TITLE
Shadow Validation Analyzer - List & diff responses that have changed

### ISSUE THREAD

**Issue by mikaylathompson** [opensearch-project/opensearch-migrations#84]
As a user, I would like to be able to run the analyzer tool and get summary statistics and a list of diffs for responses that are different between the original and shadow clusters.

### Acceptance Criteria
- Define basic file format for HAProxy logging of requests & response
- The Analyzer tool can be configured with files of the logged data cluster and run.
- The tool shows some summary statistics (number of requests, % of matching responses).
- The tool returns a list of requests that have different responses from the original and shadow clusters.
- Diffs for each response pair are available to the user.
- A list of hardcoded fields can be ignored in the comparisons (`took`, ip addresses, cluster names, etc.)

**Comment by sumobrian** [comment]
This task will have a dependency on the output of HAProxy. We need to determine how to output logs from both the source and target cluster.

**Comment by sumobrian** [comment]
Point Estimation: 5

**Comment by sumobrian** [comment]
Instead of delivering "Shadow Validator Analyzer - Apply transformation to mask volatile/unrelated fields" #86 we will handle specific cases such as latency differences as part of this task.
