### ISSUE TITLE
Shadow Validation Analyzer - Report on basic performance comparison data

### ISSUE THREAD

**Issue by mikaylathompson** [opensearch-project/opensearch-migrations#85]
As a user, I would like to be able to get basic performance comparison data between my original and shadow clusters.

### Acceptance Criteria
- When the Analyzer tool is run (as defined in #84 ), it outputs basic performance data for requests on the original vs. shadow clusters.
- Basic performance data includes average, p90, and p99 latencies, and other statistics as deemed possible & useful in the meantime.
- Latencies should be reported using the `took` field in all response for which it exists.

**Comment by sumobrian** [comment]
Output is dumped unstructured to the console.

**Comment by sumobrian** [comment]
Estimation: 3
